version: "3"
services:

  node:
    #image: "node:10.18.0"
    build: .
    restart: "unless-stopped"
    working_dir: /home/node/app
    env_file:
      - ".env"
    volumes:
      - "./api:/home/node/app"
    ports:
      - "80:3000"
    command: "/home/node/app/node_modules/.bin/nodemon index.js"

