FROM php:fpm

RUN apt-get update && apt-get install -y autotools-dev libssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && docker-php-ext-install pdo_mysql

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli



# ----- WRITE PERMISSIONS -----
# Change uid and gid in order to be the same as your host
ARG GROUP_ID=1000
ARG USER_ID=1000

RUN groupadd --gid $GROUP_ID developer
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID developer
USER developer
# ----- END - WRITE PERMISSIONS -----